---
kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "nationalparks-pipeline"
spec:
  strategy:
    type: "JenkinsPipeline"
    jenkinsPipelineStrategy:
      jenkinsfile: "node {\n  stage 'Build'\n  openshiftBuild(buildConfig: 'nationalparks', showBuildLogs: 'true')\n  \n  stage 'Deploy'\n  openshiftDeploy(deploymentConfig: 'nationalparks')\n}"
